#  Project information
site_name: 'Programming Projects'
site_description: 'Programming Notes'
site_author: 'Andrzej Zahorski'
site_url: https://codenotes.dev/


# Repository
# repo_name: ''
# repo_url: ''

# Copyright
copyright: 'Copyright &copy; 2022 Andrzej Zahorski'

# Plugins
# Plugins
plugins:
  - search
  - markmap
  # - autolinks 
  - roamlinks
  # - obsidian-bridge
#  - mknotebooks:
#      enable_default_jupyter_cell_styling: false
  - blogging:
      dirs: # The directories to be included
        - blog
      paging: false      # Disable paging




        #  - tags:
        #        tags_file: ../tags.md
  - mkdocs-jupyter:
      # execute: True
      include_source: True
      theme: dark

      # theme: slate
      # include_source: True

  - literate-nav:
      nav_file: SUMMARY.md

  # Replaced by mkdocs-material diagrams

  # - mermaid2:
      # arguments:
        # test if its __palette_1 (dark) or __palette_2 (light)
        # for mkdocs-material >=8.0.0
        # theme: |
          # ^(JSON.parse(__md_get("__palette").index == 1)) ? 'dark' : 'light'
#       for mkdocs-material <8.0.0
#         ^(JSON.parse(window.localStorage.getItem(__prefix('__palette'))).index == 1) ? 'dark' : 'light'

  # - page-to-pdf # should be last
     
  
  # - encryptcontent:
      # global_password: '5howstuff!'
      # remember_password: True
  #     decrypt_search: True



## Extensions
markdown_extensions:    
  - footnotes
  - pymdownx.highlight:
      linenums: true           
  - pymdownx.inlinehilite  
  - pymdownx.keys
  - pymdownx.snippets  
  - admonition
  - pymdownx.details  
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  # - mdx_truly_sane_lists

  # LaTeX
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
 
  # - attr_list
  # - pymdownx.arithmatex
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg


  - toc:
      permalink: true

# ================================================
#         THEME                                  #
# ================================================

theme:
  name: material
  font:
    # text: Sarala
    text: Montserrat
  features:
    # - navigation.top
    - search.suggest    
    - search.highlight     
    - search.share        
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - header.autohide
    - content.code.annotate
    # - navigation.tabs.sticky
  custom_dir: overrides






  language: 'en'
  # logo: 'images/logo.png'
  # favicon: 'images/logo.png'
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: green
      # primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
 
extra_css:
  - '../../stylesheets/extra.css'  

  
  

# Customisation
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/andynameistaken
  generator: false

    



extra_javascript:
  # LaTeX support
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # Mermaid Graph
  # - extra/refresh_on_toggle_dark_light.js         # deprecated
  # - https://unpkg.com/mermaid/dist/mermaid.min.js # deprecated
  # sortable data tables
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - /javascripts/tablesort.js
